name: Generate Wisdom Shorts

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install ffmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Pick Random Mood, Video, Music
        id: pick
        run: |
          # moods list
          moods=("Resolute")
          #  "Serene" "Inspirational" "Wise & Reflective" "Cautionary" "Sorrowful" "Humble & Grounded" "Defiant & Rebellious" "Compassionate"
          # pick random mood
          MOOD="${moods[$((RANDOM % ${#moods[@]}))]}"
          echo "Mood chosen: $MOOD"

          # pick random video
          VIDEO=$(find "assets/$MOOD/background" -type f | shuf -n1)
          echo "Video chosen: $VIDEO"

          # pick random music
          MUSIC=$(find "assets/$MOOD/music" -type f | shuf -n1)
          echo "Music chosen: $MUSIC"

          # export for next steps
          echo "mood=$MOOD" >> $GITHUB_OUTPUT
          echo "video=$VIDEO" >> $GITHUB_OUTPUT
          echo "music=$MUSIC" >> $GITHUB_OUTPUT

      - name: Generate Final Video
        run: |
          TEXT="Test Quote Overlay"
          AUTHOR="Anonymous"
          OVERLAY_TEXT="$TEXT - $AUTHOR"

          ffmpeg -i "${{ steps.pick.outputs.video }}" \
          -vf "drawtext=text='$OVERLAY_TEXT':fontcolor=white:fontsize=40:x=(w-text_w)/2:y=(h-text_h)/2" \
          -i "${{ steps.pick.outputs.music }}" \
          -filter_complex "[0:a][1:a]amix=inputs=2:duration=first:dropout_transition=2,volume=2" \
          -c:v libx264 -c:a aac -shortest final.mp4

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: hiddenember-final
          path: final.mp4
